// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI-only config (migrate, introspect). These commands cannot run through
  // a connection pooler, so they use the DIRECT (unpooled) Neon URL.
  // The app's PrismaClient connects separately using the pooled DATABASE_URL.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
